variables:
  OUT_FILE : TwrpRecovery-3.2.2.img

image: surendrajat/twrp-builder:latest

build:
    script:
    - apt-get -yy update && apt-get -y install aria2
    - aria2c -x16 -s16 -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz -d $HOME/ -o twrp.tar.xz
    - cd $HOME && tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
    - cd $HOME/twrp/ && mkdir -p device/condor/tgw_706 && mv /builds/Surendrajat/andorid_device_condor_tgw_706/* device/condor/tgw_706/
    - git clone https://github.com/TwrpBuilder/device_generic_twrpbuilder.git device/generic/twrpbuilder
    - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
    - source build/envsetup.sh && lunch omni_tgw_706-eng && make -j16 recoveryimage
    - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
    - cp $HOME/twrp/out/target/product/tgw_706/recovery.img /builds/Surendrajat/andorid_device_condor_tgw_706/${OUT_FILE}
    artifacts:
        paths: 
        - /builds/Surendrajat/andorid_device_condor_tgw_706/${OUT_FILE}